"""Initial migration

Revision ID: 34d209b48dac
Revises: 
Create Date: 2025-04-20 20:05:55.604579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34d209b48dac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('severity_recipients')
    op.drop_table('check_runs')
    op.drop_table('data_checks')
    op.drop_table('database_connections')
    op.drop_table('db_connections')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_table('check_runs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('data_check_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('run_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('severity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('result_preview', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('notification_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['data_check_id'], ['data_checks.id'], name='check_runs_data_check_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='check_runs_pkey')
    )
    op.create_table('db_connections',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('host', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('port', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('database', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('encrypted_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='db_connections_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('database_connections',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('host', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('port', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('database', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('encrypted_password', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='database_connections_pkey')
    )
    op.create_table('data_checks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('organization', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('project', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('troubleshooting_guide', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('db_connection_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sql_script', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('schedule', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expiry_period_hours', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_attachment_rows', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['db_connection_id'], ['db_connections.id'], name='data_checks_db_connection_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='data_checks_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('severity_recipients',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('data_check_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('min_severity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_severity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('emails', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['data_check_id'], ['data_checks.id'], name='severity_recipients_data_check_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='severity_recipients_pkey')
    )
    # ### end Alembic commands ###
